### ISSUE TITLE
lost sneek3 files

### ISSUE THREAD

**Issue by alex-paul-htm** [alex-paul-htm/Sneek2#1]
# Lost files for sneek3
***
They are on my home laptop's hard drive and my motherboard is fried. I am probably going to have to attempt to extract the data at some point, not sure if the drive is SATA or not if so data can be easily recovered.

**Comment by Alriceee** [comment]
rip

**Comment by alex-paul-htm** [comment]
# do you have a SATA to USB adapter spoke?
***
if so...
***
can
***
I
***
borrow
***
it

**Comment by Alriceee** [comment]
NO

**Comment by alex-paul-htm** [comment]
# meanie
***
that is very rude you need to speak in ~~spanish english~~ Russian

**Comment by Alriceee** [comment]
хорошо извини нет у меня его нет

**Comment by alex-paul-htm** [comment]
Блядь

**Comment by Alriceee** [comment]
Ыес

*Coding master*
*Email: ***@***.*** ***@***.***>*

**Comment by alex-paul-htm** [comment]
I made a new sneek from the ground up and will be adding A whole bunch of things as time goes on
